header:
  version: 19

distro: nile

env:
  BUILDNAME: "99.0.0d0"

defaults:
  repos:
    branch: "scarthgap"

local_conf_header:
  disk-space-monitoring: |
    BB_DISKMON_DIRS ??= "\
      STOPTASKS,${TMPDIR},1G,100K \
      STOPTASKS,${DL_DIR},1G,100K \
      STOPTASKS,${SSTATE_DIR},1G,100K \
      STOPTASKS,/tmp,100M,100K \
      HALT,${TMPDIR},100M,1K \
      HALT,${DL_DIR},100M,1K \
      HALT,${SSTATE_DIR},100M,1K \
      HALT,/tmp,10M,1K"

  ipk-packages: |
    PACKAGE_CLASSES ?= "package_ipk"

repos:
  meta-nile:
    path: "meta-nile"
    layers:
      .:

  bitbake:
    url: "https://git.openembedded.org/bitbake.git"
    path: "layers/bitbake"
    branch: "2.8"
    # This repo does not provide any layers.
    layers:
      .: disabled

  openembedded-core:
    url: "https://git.openembedded.org/openembedded-core.git"
    path: "layers/openembedded-core"
    layers:
      meta:
    patches:
      patch0:
        repo: meta-nile
        path: ../kas/patches/oe-core/0001-Revert-lib-oe-go-document-map_arch-and-raise-an-erro.patch

  meta-openembedded:
    url: "https://git.openembedded.org/meta-openembedded.git"
    path: "layers/meta-openembedded"
    layers:
      meta-oe:
      meta-python:
      meta-filesystems:
      meta-networking:

  meta-arm:
    url: "https://git.yoctoproject.org/meta-arm.git"
    path: "layers/meta-arm"
    layers:
      meta-arm:
      meta-arm-toolchain:
